# Generated by Django 5.2.4 on 2026-01-07 15:47

import django.db.models.deletion
import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('business_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mixed', 'Mixed')], max_length=20)),
                ('category', models.CharField(choices=[('agriculture_farming', 'Agriculture & Farming'), ('mining_extraction', 'Mining & Extraction'), ('manufacturing', 'Manufacturing'), ('construction_infrastructure', 'Construction & Infrastructure'), ('retail_wholesale', 'Retail & Wholesale'), ('food_beverage', 'Food & Beverage Services'), ('hospitality_tourism', 'Hospitality & Tourism'), ('healthcare_wellness', 'Healthcare & Wellness'), ('financial_services', 'Financial Services'), ('education_training', 'Education & Training'), ('it_ites', 'Information Technology (IT & ITeS)'), ('media_entertainment', 'Media & Entertainment'), ('logistics_transportation', 'Logistics & Transportation'), ('professional_consulting', 'Professional & Consulting Services'), ('telecommunications', 'Telecommunications'), ('energy_utilities', 'Energy & Utilities'), ('real_estate', 'Real Estate & Property Services'), ('security_safety', 'Security & Safety Services'), ('creative_design', 'Creative & Design Services'), ('non_profit', 'Non-Profit & Social Enterprises')], max_length=50)),
                ('contact_number', models.CharField(max_length=21)),
                ('applier_designation', models.CharField(max_length=100)),
                ('registration_proof', models.FileField(upload_to='uploads/registration/', validators=[ntls.models.validate_pdf])),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='uploads/address/', validators=[ntls.models.validate_address_proof])),
                ('logo', models.ImageField(upload_to='logos/', validators=[ntls.models.validate_image])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('suspended_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('services', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter the contact phone number (e.g., +91-123-456-7890)', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Enter the contact email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('form_submission', 'Form Submission'), ('status_update', 'Status Update'), ('general', 'General'), ('notifications', 'Notifications')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL identifier', unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('fixed', 'Fixed Price'), ('team', 'Team-based Pricing')], default='free', max_length=10)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('team_price_slabs', models.JSONField(blank=True, help_text="Example: {'2': 400, '3': 550, '4': 700} → price for team size", null=True)),
                ('max_team_size', models.PositiveIntegerField(default=1, help_text='Maximum members including leader')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Enter the payment link to redirect users.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200, verbose_name='College Name')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions for Students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show to Students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, verbose_name='Razorpay Key ID')),
                ('key_secret', models.CharField(max_length=100, verbose_name='Razorpay Key Secret')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Razorpay Configuration',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text="Enter Font Awesome icon class (e.g., 'fas fa-handshake') or leave blank if uploading an icon image.", max_length=50, null=True)),
                ('icon_image', models.ImageField(blank=True, help_text='Upload a custom icon image (JPG, JPEG, PNG) if preferred.', null=True, upload_to='service_icons/', validators=[ntls.models.validate_image])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('whatsapp', 'Whatsapp')], max_length=50, unique=True)),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/', validators=[ntls.models.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ntls.blog')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Leader Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone/WhatsApp')),
                ('institution', models.CharField(max_length=255, verbose_name='College/School')),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('other', 'Others')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('members', models.JSONField(blank=True, help_text="List of additional members: [{'name': ..., 'email': ..., ...}]", null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ntls.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Field Label (e.g. Full Name)')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('file', 'File Upload'), ('url', 'Link/URL')], max_length=20, verbose_name='Field Type')),
                ('options', models.TextField(blank=True, verbose_name='Dropdown Options (one per line)')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('unique_key', models.BooleanField(default=False, help_text='Check this for Roll Number, Month, etc. Student cannot submit twice with same value', verbose_name='Unique Key - Prevent Duplicate')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ntls.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='File Title')),
                ('file', models.FileField(upload_to='guidelines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='ntls.project')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ntls.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
