# Generated by Django 5.2.4 on 2025-12-02 12:43

import django.db.models.deletion
import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('business_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mixed', 'Mixed')], max_length=20)),
                ('category', models.CharField(choices=[('agriculture_farming', 'Agriculture & Farming'), ('mining_extraction', 'Mining & Extraction'), ('manufacturing', 'Manufacturing'), ('construction_infrastructure', 'Construction & Infrastructure'), ('retail_wholesale', 'Retail & Wholesale'), ('food_beverage', 'Food & Beverage Services'), ('hospitality_tourism', 'Hospitality & Tourism'), ('healthcare_wellness', 'Healthcare & Wellness'), ('financial_services', 'Financial Services'), ('education_training', 'Education & Training'), ('it_ites', 'Information Technology (IT & ITeS)'), ('media_entertainment', 'Media & Entertainment'), ('logistics_transportation', 'Logistics & Transportation'), ('professional_consulting', 'Professional & Consulting Services'), ('telecommunications', 'Telecommunications'), ('energy_utilities', 'Energy & Utilities'), ('real_estate', 'Real Estate & Property Services'), ('security_safety', 'Security & Safety Services'), ('creative_design', 'Creative & Design Services'), ('non_profit', 'Non-Profit & Social Enterprises')], max_length=50)),
                ('contact_number', models.CharField(max_length=21)),
                ('applier_designation', models.CharField(max_length=100)),
                ('registration_proof', models.FileField(upload_to='uploads/registration/', validators=[ntls.models.validate_pdf])),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='uploads/address/', validators=[ntls.models.validate_address_proof])),
                ('logo', models.ImageField(upload_to='logos/', validators=[ntls.models.validate_image])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('suspended_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('services', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter the contact phone number (e.g., +91-123-456-7890)', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Enter the contact email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('form_submission', 'Form Submission'), ('status_update', 'Status Update'), ('general', 'General'), ('notifications', 'Notifications')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Enter the payment link to redirect users.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200, verbose_name='College Name')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions for Students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_config', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text="Enter Font Awesome icon class (e.g., 'fas fa-handshake') or leave blank if uploading an icon image.", max_length=50, null=True)),
                ('icon_image', models.ImageField(blank=True, help_text='Upload a custom icon image (JPG, JPEG, PNG) if preferred.', null=True, upload_to='service_icons/', validators=[ntls.models.validate_image])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('whatsapp', 'Whatsapp')], max_length=50, unique=True)),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/', validators=[ntls.models.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ntls.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='File Name (e.g. Guidelines, Format, Policy)')),
                ('file', models.FileField(upload_to='guidelines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='ntls.project')),
            ],
        ),
    ]
