# Generated by Django 5.2.4 on 2025-12-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='form_config',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show to Students'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='title',
            field=models.CharField(help_text='e.g. Project Guidelines, Format, Policy', max_length=200, verbose_name='File Title'),
        ),
        migrations.CreateModel(
            name='ProjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Full Name, Roll Number, Month', max_length=200, verbose_name='Field Name')),
                ('field_type', models.CharField(choices=[('text', 'Short Text (Name, Roll No)'), ('textarea', 'Long Text (Address, Remarks)'), ('email', 'Email'), ('number', 'Number (Phone, Marks)'), ('date', 'Date'), ('select', 'Dropdown (Month, Department)'), ('file', 'File Upload (PDF, DOCX)'), ('url', 'Link / URL (GitHub, Drive)')], default='text', max_length=20, verbose_name='Field Type')),
                ('options', models.TextField(blank=True, help_text='Only for Dropdown: January\nFebruary\nMarch', verbose_name='Dropdown Options (one per line)')),
                ('required', models.BooleanField(default=True, verbose_name='Required Field')),
                ('order', models.PositiveIntegerField(default=0, help_text='Drag to reorder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ntls.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
