# Generated by Django 5.2.4 on 2025-07-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description',
            new_name='services',
        ),
    ]
