# Generated by Django 5.2.4 on 2025-12-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0002_alter_project_options_remove_project_form_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfield',
            name='options',
            field=models.TextField(blank=True, help_text='Only for Dropdown: Month 1\nMonth 2\nMonth 3', verbose_name='Dropdown Options (one per line)'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ntls.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
