# Generated by Django 5.2.4 on 2025-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0003_alter_projectfield_options_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfield',
            name='unique_key',
            field=models.BooleanField(default=False, help_text='Mark for fields like Roll No or Month to prevent duplicates', verbose_name='Use for Duplicate Check (e.g. Roll No, Month)'),
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('file', 'File Upload'), ('url', 'Link/URL')], max_length=20, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Field Label'),
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='options',
            field=models.TextField(blank=True, verbose_name='Dropdown Options (one per line)'),
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='File Title'),
        ),
    ]
