# Generated by Django 5.2.4 on 2025-07-25 13:23

import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='services',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='business_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='file_upload',
            field=models.FileField(upload_to='uploads/', validators=[ntls.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
    ]
