# Generated by Django 5.2.4 on 2025-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0004_projectfield_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfield',
            name='unique_key',
            field=models.BooleanField(default=False, help_text='Check this for fields like Roll Number, Month, etc. to stop duplicate submissions', verbose_name='Unique Key (Prevent Duplicate)'),
        ),
    ]
