# Generated by Django 5.2.4 on 2025-07-25 15:02

import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0005_rename_services_partner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[ntls.models.validate_image]),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
