# Generated by Django 5.2.4 on 2025-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0007_alter_business_options_alter_consumer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('suspension_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suspended Partner',
                'verbose_name_plural': 'Suspended Partners',
            },
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspend', 'Suspended')], default='pending', max_length=20),
        ),
    ]
