# Generated by Django 5.2.4 on 2025-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0009_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='SuspendedPartner',
        ),
        migrations.AddField(
            model_name='business',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='suspended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
