# Generated by Django 5.2.4 on 2025-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0010_delete_partner_delete_suspendedpartner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='approved_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='suspended_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
