# Generated by Django 5.2.4 on 2025-07-27 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0011_alter_business_approved_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(default='smtp.zoho.com', max_length=100)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('form_submission', 'Form Submission'), ('status_update', 'Status Update'), ('general', 'General'), ('notifications', 'Notifications')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='submission_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='services',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='submission_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='submission_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='suspended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
