# Generated by Django 5.2.4 on 2025-07-30 04:16

import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0012_emailconfig_alter_business_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='budget',
        ),
        migrations.AddField(
            model_name='business',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/address/', validators=[ntls.models.validate_address_proof]),
        ),
        migrations.AddField(
            model_name='business',
            name='applier_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('mixed', 'Mixed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('bangalore', 'Bangalore'), ('mumbai', 'Mumbai'), ('delhi', 'Delhi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/registration/', validators=[ntls.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, choices=[('tamil_nadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('maharashtra', 'Maharashtra'), ('delhi', 'Delhi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, choices=[('agriculture_farming', 'Agriculture & Farming'), ('mining_extraction', 'Mining & Extraction'), ('manufacturing', 'Manufacturing'), ('construction_infrastructure', 'Construction & Infrastructure'), ('retail_wholesale', 'Retail & Wholesale'), ('food_beverage', 'Food & Beverage Services'), ('hospitality_tourism', 'Hospitality & Tourism'), ('healthcare_wellness', 'Healthcare & Wellness'), ('financial_services', 'Financial Services'), ('education_training', 'Education & Training'), ('it_ites', 'Information Technology (IT & ITeS)'), ('media_entertainment', 'Media & Entertainment'), ('logistics_transportation', 'Logistics & Transportation'), ('professional_consulting', 'Professional & Consulting Services'), ('telecommunications', 'Telecommunications'), ('energy_utilities', 'Energy & Utilities'), ('real_estate', 'Real Estate & Property Services'), ('security_safety', 'Security & Safety Services'), ('creative_design', 'Creative & Design Services'), ('non_profit', 'Non-Profit & Social Enterprises')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
    ]
