# Generated by Django 5.2.4 on 2025-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0013_remove_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
