# Generated by Django 5.2.4 on 2025-07-30 10:54

import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0014_alter_business_district_alter_business_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs/', validators=[ntls.models.validate_image])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
