# Generated by Django 5.2.4 on 2025-07-30 11:26

import django.db.models.deletion
import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0015_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/', validators=[ntls.models.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ntls.blog')),
            ],
        ),
    ]
