# Generated by Django 5.2.4 on 2025-08-01 05:07

import ntls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0017_service_socialplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a custom icon image (JPG, JPEG, PNG) if preferred.', null=True, upload_to='service_icons/', validators=[ntls.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Enter Font Awesome icon class (e.g., 'fas fa-handshake') or leave blank if uploading an icon image.", max_length=50, null=True),
        ),
    ]
