# Generated by Django 5.2.4 on 2025-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0018_service_icon_image_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Enter the payment link to redirect users.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
