# Generated by Django 5.2.4 on 2025-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0019_paymentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter the contact phone number (e.g., +91-123-456-7890)', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Enter the contact email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
