# Generated by Django 5.2.4 on 2025-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntls', '0020_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contact_number',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
